[build]
command = "npm run build" # Replace with your build command
publish = "." # Replace with your static files directory

[context.production]
command = "npm start" # Replace with your start command

[context.development]
command = "npm start" # Replace with your start command
